language: c

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list

install:
  - sudo apt-get update > /dev/null
  - sudo apt-get build-dep f-spot > /dev/null
  - sudo apt-get install mono-devel mono-gmcs > /dev/null
  - sudo apt-get install libdbus-glib1.0-cil-dev libgnomedesktop2.0-cil-dev libgnome-desktop-dev liblcms2-dev > /dev/null
  - sudo apt-get install libgtk-sharp-beans2.0-cil-dev libgio2.0-cil-dev > /dev/null

script:
  - ./autogen.sh
  - cd build
  - make
  - cd ../lib/libfspot
  - make
  - cd ../..
  - xbuild F-Spot.sln
