sudo: required
dist: xenial
language: csharp
mono:
  - latest
solution: F-Spot.sln

install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt install -qq automake libtool intltool nuget liblcms2-dev libjpeg-dev libunique-dev adwaita-icon-theme gnome-doc-utils > /dev/null
  - sudo apt install -qq libglib2.0-cil-dev libglib2.0-dev libgconf2-dev libgconf2.0-cil-dev libgtk2.0-cil-dev libgnome2.0-cil-dev libgnome-keyring1.0-cil-dev > /dev/null
  - sudo apt install -qq gtk-sharp2-gapi libgtk-sharp-beans2.0-cil-dev libgio2.0-cil-dev > /dev/null

script:
  - ./autogen.sh --enable-tests
  - make
  - nuget restore .nuget/packages.config -PackagesDirectory packages
  - make test
